//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntrepriseDeDistribution
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depot
    {
        public Depot()
        {
            this.Stocks = new HashSet<Stock>();
        }
    
        public int Numero_Depot { get; set; }
        public string Nom_Depot { get; set; }
        public string Code_Region { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
