//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntrepriseDeDistribution
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livre
    {
        public Livre()
        {
            this.Editions = new HashSet<Edition>();
            this.Stocks = new HashSet<Stock>();
            this.Ecrivains = new HashSet<Ecrivain>();
        }
    
        public int Numero_Livre { get; set; }
        public string Nom_Livre { get; set; }
        public Nullable<int> Numero_Theme { get; set; }
    
        public virtual ICollection<Edition> Editions { get; set; }
        public virtual Theme Theme { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
        public virtual ICollection<Ecrivain> Ecrivains { get; set; }
    }
}
