//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntrepriseDeDistribution
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntrepriseEntities : DbContext
    {
        public EntrepriseEntities()
            : base("name=EntrepriseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Depot> Depots { get; set; }
        public DbSet<Ecrivain> Ecrivains { get; set; }
        public DbSet<Editeur> Editeurs { get; set; }
        public DbSet<Edition> Editions { get; set; }
        public DbSet<Livre> Livres { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<Stock> Stocks { get; set; }
        public DbSet<Theme> Themes { get; set; }
        public DbSet<V_Recherche> V_Recherche { get; set; }
        public DbSet<V_graphe> V_graphe { get; set; }
    }
}
