//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntrepriseDeDistribution
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.Depots = new HashSet<Depot>();
        }
    
        public string Code_Region { get; set; }
        public string Nom_Region { get; set; }
        public Nullable<int> Population { get; set; }
    
        public virtual ICollection<Depot> Depots { get; set; }
    }
}
