//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntrepriseDeDistribution
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theme
    {
        public Theme()
        {
            this.Livres = new HashSet<Livre>();
        }
    
        public int Numero_Theme { get; set; }
        public string Nom_Theme { get; set; }
    
        public virtual ICollection<Livre> Livres { get; set; }
    }
}
