//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntrepriseDeDistribution
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_graphe
    {
        public int Numero_Depot { get; set; }
        public string Nom_Depot { get; set; }
        public Nullable<int> Total_en_stock { get; set; }
    }
}
