//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntrepriseDeDistribution
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Recherche
    {
        public int Numero_Livre { get; set; }
        public string Nom_Livre { get; set; }
        public Nullable<int> Numero_Theme { get; set; }
        public Nullable<System.DateTime> Annee_D_edition { get; set; }
    }
}
